/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2d3133",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed": "#131b2e",
        "surface-tint": "#006398",
        "tertiary-fixed": "#dae2fd",
        "on-surface-variant": "#3f4850",
        "on-primary": "#ffffff",
        "on-secondary-container": "#54647a",
        "surface": "#f7f9fb",
        "on-tertiary-fixed-variant": "#3f465c",
        "error": "#ba1a1a",
        "outline": "#707881",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed-dim": "#bec6e0",
        "surface-container-low": "#f2f4f6",
        "on-primary-fixed": "#001d31",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed": "#0b1c30",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef0",
        "secondary": "#505f76",
        "background": "#f7f9fb",
        "on-secondary-fixed-variant": "#38485d",
        "surface-dim": "#d8dadc",
        "primary": "#006194",
        "secondary-fixed-dim": "#b7c8e1",
        "on-primary-fixed-variant": "#004b73",
        "on-primary-container": "#fdfcff",
        "secondary-fixed": "#d3e4fe",
        "primary-fixed-dim": "#93ccff",
        "inverse-primary": "#93ccff",
        "surface-container-high": "#e6e8ea",
        "outline-variant": "#bfc7d2",
        "tertiary-container": "#6c748b",
        "secondary-container": "#d0e1fb",
        "primary-fixed": "#cce5ff",
        "primary-container": "#007bb9",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1e",
        "on-tertiary-container": "#fefcff",
        "tertiary": "#545c72",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "topbar-height": "64px",
        "container-padding-mobile": "16px",
        "container-padding-desktop": "32px",
        "sidebar-width": "260px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "stats-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "stats-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
