// Comprehensive Mock Data for seamless offline / VS Code standalone operation

export const mockStats = {
  totalPatients: 8,
  totalDoctors: 4,
  todayAppointments: 5,
  pendingBills: 2,
  totalRevenue: 15500,
};

export const mockPatients = [
  {
    id: 1,
    patientCode: 'PT-1001',
    fullName: 'Michael Chang',
    dob: '1979-05-14',
    age: 45,
    gender: 'Male',
    bloodGroup: 'O+',
    phone: '+1 (555) 123-4567',
    email: 'michael.chang@email.com',
    address: '742 Evergreen Terrace, Springfield',
    emergencyContact: '+1 (555) 999-1111',
    medicalHistory: 'Hypertension diagnosed in 2021. Regular checkup.',
    allergies: 'Penicillin, Latex (Mild)',
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    patientCode: 'PT-1002',
    fullName: 'Sarah Jenkins',
    dob: '1996-08-22',
    age: 28,
    gender: 'Female',
    bloodGroup: 'A-',
    phone: '+1 (555) 987-6543',
    email: 'sarah.j@email.com',
    address: '123 Maple Street, Cityville',
    emergencyContact: '+1 (555) 888-2222',
    medicalHistory: 'Mild asthma, managed with Inhaler.',
    allergies: 'Sulfa Drugs',
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    patientCode: 'PT-1003',
    fullName: 'Robert Johnson',
    dob: '1962-11-03',
    age: 62,
    gender: 'Male',
    bloodGroup: 'B+',
    phone: '+1 (555) 345-6789',
    email: 'robert.j@email.com',
    address: '456 Oak Avenue, Metropolis',
    emergencyContact: '+1 (555) 777-3333',
    medicalHistory: 'Type 2 Diabetes since 2018.',
    allergies: 'None reported',
    status: 'Inactive',
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    patientCode: 'PT-1004',
    fullName: 'Eleanor Vance',
    dob: '1985-02-19',
    age: 39,
    gender: 'Female',
    bloodGroup: 'AB+',
    phone: '+1 (555) 234-5678',
    email: 'eleanor.vance@email.com',
    address: '89 Hill House Lane, Boston',
    emergencyContact: '+1 (555) 666-4444',
    medicalHistory: 'Migraine headaches.',
    allergies: 'Aspirin',
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    patientCode: 'PT-1005',
    fullName: 'Marcus Holloway',
    dob: '1992-09-30',
    age: 32,
    gender: 'Male',
    bloodGroup: 'O-',
    phone: '+1 (555) 876-5432',
    email: 'marcus.h@email.com',
    address: '505 Bay Street, San Francisco',
    emergencyContact: '+1 (555) 555-5555',
    medicalHistory: 'ACL Knee Reconstruction in 2020.',
    allergies: 'Ibuprofen',
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    patientCode: 'PT-1006',
    fullName: 'Sophia Chen',
    dob: '2016-04-12',
    age: 8,
    gender: 'Female',
    bloodGroup: 'A+',
    phone: '+1 (555) 432-1098',
    email: 'parent.chen@email.com',
    address: '321 Pine Road, Seattle',
    emergencyContact: '+1 (555) 444-6666',
    medicalHistory: 'Pediatric seasonal allergies.',
    allergies: 'Peanuts (Severe)',
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 7,
    patientCode: 'PT-1007',
    fullName: 'James Wilson',
    dob: '1970-12-05',
    age: 53,
    gender: 'Male',
    bloodGroup: 'B-',
    phone: '+1 (555) 654-3210',
    email: 'j.wilson@email.com',
    address: '789 Cedar Drive, Chicago',
    emergencyContact: '+1 (555) 333-7777',
    medicalHistory: 'Coronary artery disease history.',
    allergies: 'Codeine',
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 8,
    patientCode: 'PT-1008',
    fullName: 'Clara Oswald',
    dob: '1994-11-23',
    age: 29,
    gender: 'Female',
    bloodGroup: 'O+',
    phone: '+1 (555) 789-0123',
    email: 'clara.o@email.com',
    address: '42 Time Vortex Way, London',
    emergencyContact: '+1 (555) 222-8888',
    medicalHistory: 'Routine wellness checkups.',
    allergies: 'None',
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
];

export const mockDoctors = [
  {
    id: 1,
    doctorCode: 'DOC-2001',
    fullName: 'Dr. Robert Chen',
    email: 'r.chen@vitalsync.com',
    phone: '+1 (555) 123-4567',
    specialization: 'Cardiology',
    qualification: 'MD, FACC',
    experience: '15 Years',
    availableDays: 'Mon, Wed, Fri',
    availableTime: '09:00 AM - 05:00 PM',
    status: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    doctorCode: 'DOC-2002',
    fullName: 'Dr. Emily Stanton',
    email: 'e.stanton@vitalsync.com',
    phone: '+1 (555) 987-6543',
    specialization: 'Pediatrics',
    qualification: 'MD, FAAP',
    experience: '10 Years',
    availableDays: 'Tue, Thu, Sat',
    availableTime: '08:00 AM - 04:00 PM',
    status: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1594824813689-d603247475f4?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    doctorCode: 'DOC-2003',
    fullName: 'Dr. Marcus Vance',
    email: 'm.vance@vitalsync.com',
    phone: '+1 (555) 456-7890',
    specialization: 'Neurology',
    qualification: 'MD, PhD',
    experience: '18 Years',
    availableDays: 'Mon - Fri',
    availableTime: '10:00 AM - 06:00 PM',
    status: 'In Surgery',
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    doctorCode: 'DOC-2004',
    fullName: 'Dr. Sarah Mitchell',
    email: 's.mitchell@vitalsync.com',
    phone: '+1 (555) 321-7654',
    specialization: 'General Practice',
    qualification: 'MBBS, MD',
    experience: '12 Years',
    availableDays: 'Mon - Sat',
    availableTime: '09:00 AM - 05:00 PM',
    status: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
  },
];

export const mockAppointments = [
  {
    id: 1,
    appointmentCode: 'APT-2045',
    patientId: 1,
    doctorId: 1,
    patient: mockPatients[0],
    doctor: mockDoctors[0],
    patientName: 'Michael Chang',
    doctorName: 'Dr. Robert Chen',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '09:00 AM',
    reason: 'Routine Cardiac Evaluation',
    notes: 'Patient reported mild chest tightness.',
    status: 'Confirmed',
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    appointmentCode: 'APT-2046',
    patientId: 2,
    doctorId: 2,
    patient: mockPatients[1],
    doctor: mockDoctors[1],
    patientName: 'Sarah Jenkins',
    doctorName: 'Dr. Emily Stanton',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '09:30 AM',
    reason: 'General Wellness Check',
    notes: 'Followup after pediatric fever.',
    status: 'In Progress',
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    appointmentCode: 'APT-2047',
    patientId: 6,
    doctorId: 2,
    patient: mockPatients[5],
    doctor: mockDoctors[1],
    patientName: 'Sophia Chen',
    doctorName: 'Dr. Emily Stanton',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '10:15 AM',
    reason: 'Allergy Followup',
    notes: 'Routine checkup for asthma inhaler refill.',
    status: 'Scheduled',
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    appointmentCode: 'APT-2048',
    patientId: 7,
    doctorId: 1,
    patient: mockPatients[6],
    doctor: mockDoctors[0],
    patientName: 'James Wilson',
    doctorName: 'Dr. Robert Chen',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '11:00 AM',
    reason: 'Urgent BP Spiking Evaluation',
    notes: 'BP reading 160/100 at home.',
    status: 'Urgent',
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    appointmentCode: 'APT-2049',
    patientId: 4,
    doctorId: 3,
    patient: mockPatients[3],
    doctor: mockDoctors[2],
    patientName: 'Eleanor Vance',
    doctorName: 'Dr. Marcus Vance',
    appointmentDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    appointmentTime: '02:00 PM',
    reason: 'Neurology Consultation for Migraine',
    notes: 'Evaluated for chronic headaches.',
    status: 'Scheduled',
    createdAt: new Date().toISOString(),
  },
];

export const mockPrescriptions = [
  {
    id: 1,
    prescriptionCode: 'RX-4001',
    patientId: 1,
    doctorId: 1,
    patient: mockPatients[0],
    doctor: mockDoctors[0],
    patientName: 'Michael Chang',
    doctorName: 'Dr. Robert Chen',
    prescriptionDate: new Date().toISOString().split('T')[0],
    symptoms: 'Mild chest tightness, elevated blood pressure',
    diagnosis: 'Stage 1 Primary Hypertension',
    instructions: 'Take medications after breakfast. Avoid salt heavy foods.',
    followUpDate: new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
    medicines: [
      { id: 1, medicineName: 'Amoxicillin 500mg', dosage: '1 Tab', frequency: '1-0-1 (BID)', duration: '7 Days' },
      { id: 2, medicineName: 'Lisinopril 10mg', dosage: '1 Tab', frequency: '1-0-0 (OD)', duration: '30 Days' },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    prescriptionCode: 'RX-4002',
    patientId: 2,
    doctorId: 2,
    patient: mockPatients[1],
    doctor: mockDoctors[1],
    patientName: 'Sarah Jenkins',
    doctorName: 'Dr. Emily Stanton',
    prescriptionDate: new Date().toISOString().split('T')[0],
    symptoms: 'Sore throat, mild fever',
    diagnosis: 'Upper Respiratory Tract Infection',
    instructions: 'Complete full antibiotic course. Drink plenty of warm fluids.',
    followUpDate: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    medicines: [
      { id: 3, medicineName: 'Paracetamol 500mg', dosage: '1 Tab', frequency: '1-1-1 (TID)', duration: '5 Days' },
    ],
    createdAt: new Date().toISOString(),
  },
];

export const mockBills = [
  {
    id: 1,
    billCode: 'INV-2023-001',
    patientId: 1,
    doctorId: 1,
    patient: mockPatients[0],
    doctor: mockDoctors[0],
    patientName: 'Michael Chang',
    doctorName: 'Dr. Robert Chen',
    billDate: new Date().toISOString().split('T')[0],
    consultationFee: 100.0,
    medicineCharges: 45.0,
    otherCharges: 15.0,
    discount: 10.0,
    tax: 5.0,
    totalAmount: 155.0,
    paymentMethod: 'Credit Card',
    paymentStatus: 'Paid',
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    billCode: 'INV-2023-002',
    patientId: 2,
    doctorId: 2,
    patient: mockPatients[1],
    doctor: mockDoctors[1],
    patientName: 'Sarah Jenkins',
    doctorName: 'Dr. Emily Stanton',
    billDate: new Date().toISOString().split('T')[0],
    consultationFee: 80.0,
    medicineCharges: 25.5,
    otherCharges: 35.0,
    discount: 20.0,
    tax: 0.0,
    totalAmount: 120.5,
    paymentMethod: 'Cash',
    paymentStatus: 'Pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    billCode: 'INV-2023-003',
    patientId: 3,
    doctorId: 3,
    patient: mockPatients[2],
    doctor: mockDoctors[2],
    patientName: 'Robert Johnson',
    doctorName: 'Dr. Marcus Vance',
    billDate: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    consultationFee: 150.0,
    medicineCharges: 120.0,
    otherCharges: 50.0,
    discount: 0.0,
    tax: 15.0,
    totalAmount: 335.0,
    paymentMethod: 'Insurance',
    paymentStatus: 'Pending',
    createdAt: new Date().toISOString(),
  },
];

export const mockHospitalSettings = {
  id: 1,
  hospitalName: 'VitalSync Multi-Specialty Hospital',
  phone: '+91 (800) 123-4567',
  email: 'info@vitalsync.com',
  address: 'Medical Center Road, Healthcare City, MH 400001',
  registrationNumber: 'VS-HOSP-2026-IND',
  invoiceFooter: 'Thank you for trusting VitalSync Healthcare. Get well soon!',
  updatedAt: new Date().toISOString(),
};
