/**
 * VitalSync HMS - Resilient Hospital Showcase Data
 * Ensures doctors, departments, and live bed & ICU availability always render gracefully
 * even if the cloud backend is cold-starting or sleeping on Render free tier.
 */

export const FALLBACK_DOCTORS = [
  {
    id: 1,
    doctorCode: 'DOC-2001',
    fullName: 'Dr. Robert Chen',
    specialization: 'Cardiology',
    qualification: 'MD, FACC',
    experience: '15 Years',
    departmentName: 'Cardiology',
    availableDays: 'Mon, Wed, Fri',
    availableTime: '09:00 AM - 05:00 PM',
    consultationFee: '150.00',
    status: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 2,
    doctorCode: 'DOC-2002',
    fullName: 'Dr. Emily Stanton',
    specialization: 'Pediatrics',
    qualification: 'MD, FAAP',
    experience: '10 Years',
    departmentName: 'Pediatrics',
    availableDays: 'Tue, Thu, Sat',
    availableTime: '08:00 AM - 04:00 PM',
    consultationFee: '120.00',
    status: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1594824813628-98e6a2eb67e7?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 3,
    doctorCode: 'DOC-2003',
    fullName: 'Dr. Marcus Vance',
    specialization: 'Neurology',
    qualification: 'MD, PhD',
    experience: '18 Years',
    departmentName: 'Neurology',
    availableDays: 'Mon - Fri',
    availableTime: '10:00 AM - 06:00 PM',
    consultationFee: '180.00',
    status: 'In Surgery',
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&h=150&fit=crop&crop=face',
  },
  {
    id: 4,
    doctorCode: 'DOC-2004',
    fullName: 'Dr. Sarah Mitchell',
    specialization: 'General Practice',
    qualification: 'MBBS, MD',
    experience: '12 Years',
    departmentName: 'General Practice',
    availableDays: 'Mon - Sat',
    availableTime: '09:00 AM - 05:00 PM',
    consultationFee: '100.00',
    status: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop&crop=face',
  },
];

export const FALLBACK_DEPARTMENTS = [
  {
    id: 1,
    departmentCode: 'DEP-001',
    name: 'Cardiology',
    description: 'Specialized comprehensive cardiovascular diagnostics and catheter interventions.',
    headDoctorName: 'Dr. Robert Chen',
    totalBeds: 5,
    availableBeds: 4,
    occupiedBeds: 1,
    status: 'Active',
  },
  {
    id: 2,
    departmentCode: 'DEP-002',
    name: 'Neurology',
    description: 'Comprehensive neurological, stroke management, and neurosurgical clinical care.',
    headDoctorName: 'Dr. Marcus Vance',
    totalBeds: 10,
    availableBeds: 10,
    occupiedBeds: 0,
    status: 'Active',
  },
  {
    id: 3,
    departmentCode: 'DEP-003',
    name: 'Pediatrics',
    description: 'Specialized pediatric medicine, neonatal care (NICU), and adolescent health.',
    headDoctorName: 'Dr. Emily Stanton',
    totalBeds: 12,
    availableBeds: 12,
    occupiedBeds: 0,
    status: 'Active',
  },
  {
    id: 4,
    departmentCode: 'DEP-004',
    name: 'General Medicine',
    description: 'Primary outpatient consultations and inpatient internal medicine management.',
    headDoctorName: 'Dr. Sarah Mitchell',
    totalBeds: 15,
    availableBeds: 11,
    occupiedBeds: 4,
    status: 'Active',
  },
  {
    id: 5,
    departmentCode: 'DEP-005',
    name: 'Emergency & Trauma',
    description: '24/7 Level-1 Emergency, resuscitation bays, and acute critical trauma center.',
    headDoctorName: 'Dr. Sarah Mitchell',
    totalBeds: 8,
    availableBeds: 6,
    occupiedBeds: 2,
    status: 'Active',
  },
  {
    id: 6,
    departmentCode: 'DEP-006',
    name: 'Intensive Care Unit (ICU)',
    description: 'State-of-the-art continuous hemodynamic monitoring and invasive life support.',
    headDoctorName: 'Dr. Robert Chen',
    totalBeds: 10,
    availableBeds: 6,
    occupiedBeds: 4,
    status: 'Active',
  },
  {
    id: 7,
    departmentCode: 'DEP-007',
    name: 'Orthopedics',
    description: 'Musculoskeletal surgical care, joint replacement, arthroscopy, and rehabilitation.',
    headDoctorName: 'Dr. Marcus Vance',
    totalBeds: 10,
    availableBeds: 10,
    occupiedBeds: 0,
    status: 'Active',
  },
  {
    id: 8,
    departmentCode: 'DEP-008',
    name: 'General Surgery',
    description: 'Advanced laparoscopic, minimally invasive, and major surgical procedures.',
    headDoctorName: 'Dr. Sarah Mitchell',
    totalBeds: 12,
    availableBeds: 12,
    occupiedBeds: 0,
    status: 'Active',
  },
  {
    id: 9,
    departmentCode: 'DEP-009',
    name: 'Radiology & Imaging',
    description: 'High-field MRI, 128-slice CT, digital fluoroscopy, and diagnostic ultrasound.',
    headDoctorName: 'Dr. Emily Stanton',
    totalBeds: 5,
    availableBeds: 5,
    occupiedBeds: 0,
    status: 'Active',
  },
  {
    id: 10,
    departmentCode: 'DEP-010',
    name: 'Pathology & Diagnostics',
    description: 'Automated clinical biochemistry, hematology, and histopathology testing.',
    headDoctorName: 'Dr. Robert Chen',
    totalBeds: 0,
    availableBeds: 0,
    occupiedBeds: 0,
    status: 'Active',
  },
  {
    id: 11,
    departmentCode: 'DEP-011',
    name: 'Pharmacy',
    description: '24/7 inpatient prescription dispensing and medication therapy management.',
    headDoctorName: 'Dr. Sarah Mitchell',
    totalBeds: 0,
    availableBeds: 0,
    occupiedBeds: 0,
    status: 'Active',
  },
  {
    id: 12,
    departmentCode: 'DEP-012',
    name: 'Oncology',
    description: 'Medical oncology, chemotherapy infusion suite, and specialized palliative care.',
    headDoctorName: 'Dr. Marcus Vance',
    totalBeds: 8,
    availableBeds: 8,
    occupiedBeds: 0,
    status: 'Active',
  },
];

export const FALLBACK_BED_STATS = {
  totalBeds: 38,
  availableBeds: 27,
  occupiedBeds: 10,
  totalIcuBeds: 10,
  availableIcuBeds: 6,
  totalEmergencyBeds: 8,
  availableEmergencyBeds: 6,
  totalGeneralBeds: 15,
  availableGeneralBeds: 11,
  availableByType: {
    ICU: 6,
    EMERGENCY: 6,
    GENERAL: 11,
    PRIVATE: 4,
    SEMI_PRIVATE: 0,
  },
  totalByType: {
    ICU: 10,
    EMERGENCY: 8,
    GENERAL: 15,
    PRIVATE: 5,
    SEMI_PRIVATE: 0,
  },
};

export const FALLBACK_HOSPITAL_INFO = {
  hospitalName: 'VitalSync Multi-Specialty Hospital',
  phone: '+91 (800) 123-4567',
  emergencyNumber: '8797254899',
  ambulanceNumber: '7888834943',
  helpCenterNumber: '+91 (800) 123-4567',
  email: 'info@vitalsync.com',
  address: 'Medical Center Road, Healthcare City, MH 400001',
  registrationNumber: 'VS-HOSP-2026-IND',
  invoiceFooter: 'Thank you for trusting VitalSync Healthcare. Get well soon!',
};
